### ISSUE TITLE
Create a docker image for the dev version

### ISSUE THREAD

**Issue by bernhard-42** [bernhard-42/jupyter-cadquery#28]
To avoid `conda/...` whenever there are significant changes in `cadquery` or `jupyter-cadquery`, release a docker image "-master"

**Comment by nedtwigg** [comment]
If this happens, big vote for `1.1.0-master`, rather than moving `master` around.  Very helpful to have a repeatable setup.

**Comment by bernhard-42** [comment]
@nedtwigg Good news, a dev version is available on docker hub `bwalter42/jupyter_cadquery:2.0.0-beta2` 
It comes with the latest CadQuery (including assemblies), supports assemblies out of the box and comes wth its own mate based assembly (`MAssemby`) which can be used to also animate your CAD Assemblies. (see gif on top of the Readme)
It will be stable, since new every docker images will get the version number of the git tag.
Hope that helps

**Comment by nedtwigg** [comment]
Huzzah, thanks very much! I stopped work on my little project because of this hangup, and now I'll start it again!

**Comment by bernhard-42** [comment]
@nedtwigg Just release 2.0.0, also as a docker image. It uses the latest stable CadQuery 2.1 now

**Comment by bernhard-42** [comment]
Closing, as I regularly release new docker containers now
