### ISSUE TITLE
Displaying compounds

### ISSUE THREAD

**Issue by Shimwell** [bernhard-42/jupyter-cadquery#39]
Just experimenting with this really nice package and stumbled along this error when trying to show a compound

Wondering if here could be a special case for handling cadquery compounds in this section of the code as I don't think they have a .val() attribute

trying the show() function with ```pip install jupyter-cadquery==2.0.0-rc1``` and also tried adding ```pip install git+https://github.com/bernhard-42/cadquery-massembly```

```python
~/anaconda3/lib/python3.8/site-packages/jupyter_cadquery/cadquery/cad_objects.py in show(render_mates, mate_scale, *cad_objs, **kwargs)
    359     mate_scale = mate_scale or get_default("mate_scale")
    360 
--> 361     assembly = to_assembly(*cad_objs, render_mates=render_mates, mate_scale=mate_scale)
    362 
    363     if assembly is None:

~/anaconda3/lib/python3.8/site-packages/jupyter_cadquery/cadquery/cad_objects.py in to_assembly(render_mates, mate_scale, *cad_objs)
    310             assembly.add_list(_from_vector(cad_obj, obj_id))
    311 
--> 312         elif isinstance(cad_obj.val(), Vector):
    313             assembly.add_list(_from_vectorlist(cad_obj, obj_id))
    314 

AttributeError: 'Compound' object has no attribute 'val'
```

**Comment by bernhard-42** [comment]
@Shimwell This is a bug.
Currently, if want to view a Compound, please use `cq.Workplane(compund)`
I'll look into it for the next version (release candidate already out, so shouldn't take a long time)

**Comment by Shimwell** [comment]
Thanks very much for take a look and providing a solution in the meantime. Much appreciated

**Comment by bernhard-42** [comment]
It's actually pretty simple to fix. It will definitely be in the next release :-)

**Comment by bernhard-42** [comment]
@Shimwell Just released 2.0.0
Compounds will render correctly

**Comment by Shimwell** [comment]
Thanks for adding that compound feature @bernhard-42  I've just installed version 2.0.0 and can confirm it works nicely over here

![Screenshot from 2021-03-06 22-01-54](https://user-images.githubusercontent.com/8583900/110222082-a3679b80-7ec7-11eb-8941-79e52060f087.png)

**Comment by bernhard-42** [comment]
@Shimwell Not that I understand anything of this, but it looks nice and I thought to share how you can build colored models with `jupyter-cadquery`. Maybe you knew that anyhow, but I was actually curious how it would look like, so I gave it a try ;-)

```python
parts = []

colors = {
    "Plasma": (153, 50, 204),
    "CenterColumnShieldCylinder": (0, 0, 139),
    "BlanketFP": (102, 205, 170),
    "RotateStraightShape": (139, 0, 0),
    "ToroidalFieldCoilCoatHanger": (0, 0, 139),
    "PoloidalFieldCoilSet": (139, 0, 0),
    "PoloidalFieldCoilCaseSetFC": (128, 128, 0)
}

for shape_or_compound in my_reactor.shapes_and_components:
    name = shape_or_compound.__class__.__name__
    if isinstance(
            shape_or_compound.solid,
            (cq.occ_impl.shapes.Shape, cq.occ_impl.shapes.Compound)):
        for i, solid in enumerate(shape_or_compound.solid.Solids()):
            parts.append(Part(solid, name=f"{name}{i}", color=colors[name]))
    else:
        parts.append(Part(shape_or_compound.solid.val(), name=f"{name}", color=colors[name]))

PartGroup(parts)
```

![image](https://user-images.githubusercontent.com/954408/110381042-3edc4600-8059-11eb-9977-eef810530806.png)

![image](https://user-images.githubusercontent.com/954408/110381505-d346a880-8059-11eb-890a-0f56475f0abf.png)

**Comment by Shimwell** [comment]
This is perfect timing and we were just looking for a way to color the components, we have a growing collection of reactors and the manual coloring was really starting to add up.

bernhard-42 has just shown us the way

@RemDelaporteMathurin and @billingsley-john I vote we add default RGB colors to all the parametric components and then we can remake this without having to do it manually and perhaps some of the images in the docs can be automated as well

**Comment by bernhard-42** [comment]
@Shimwell @RemDelaporteMathurin @billingsley-john 

Final comment: `Part`/`PartGroup` are  helpers in `jupyter_cadquery` that don't exist in CQ-Editor. 
To be more independent from the coding environment, you could use the CadQuery class `Assembly` (see https://cadquery.readthedocs.io/en/latest/assy.html ), which allows colors and can be visualised in both `jupyter_cadquery` and `CQ-DEditor`. Difference to the former solution is that names need to be unique:

```python
import cadquery as cq
from jupyter_cadquery.cadquery import show

import paramak

my_reactor = paramak.SingleNullSubmersionTokamak( ... )

assembly = cq.Assembly()
C = lambda *rgb: cq.Color(*[c/255 for c in rgb])

colors = {
    "Plasma": C(153, 50, 204),
    "CenterColumnShieldCylinder": C(0, 0, 139),
    "BlanketFP": C(102, 205, 170),
    "RotateStraightShape": C(139, 0, 0),
    "ToroidalFieldCoilCoatHanger": C(0, 0, 139),
    "PoloidalFieldCoilSet": C(139, 0, 0),
    "PoloidalFieldCoilCaseSetFC": C(128, 128, 0)
}

for k, shape_or_compound in enumerate(my_reactor.shapes_and_components):
    name = shape_or_compound.__class__.__name__
    if isinstance(
            shape_or_compound.solid,
            (cq.occ_impl.shapes.Shape, cq.occ_impl.shapes.Compound)):
        for i, solid in enumerate(shape_or_compound.solid.Solids()):
            assembly.add(solid, name=f"{k}_{name}{i}", color=colors[name])
    else:
        assembly.add(shape_or_compound.solid.val(), name=f"{k}_{name}", color=colors[name])


# show_object(assembly)   # CQ Editor
assembly                  # Jupyter_cadquery
```

![image](https://user-images.githubusercontent.com/954408/110752485-a22acb80-8245-11eb-9b58-20a37dd0584c.png)

I would even say, it could be worth considering to use `Assembly` as the internal container in `paramak` (and if you place the objects correct at the beginning, you wouldn't need to describe constraints and solve the assembly. It would just serve as nice container).
