### ISSUE TITLE
Is it possible to label x,y of the grid in viewer window?

### ISSUE THREAD

**Issue by zxo102** [bernhard-42/jupyter-cadquery#51]
As shown below,   Is it possible to label the grid in viewer window with coordinates, for example, x-y?
<img width="878" alt="grid_label_issue" src="https://user-images.githubusercontent.com/9945043/132926475-23d100c2-c9b8-4cb2-8a73-ff50976eb3de.png">

It seems the grid is implemented in jupyter_cadquery.cad_helpers.Grid . 

Thanks for any help.

**Comment by bernhard-42** [comment]
@zxo102 This is not possible (and not planned). The color of the axis together with the description in the info box determines the type of grid.
