### ISSUE TITLE
jcv - naming items in the tree

### ISSUE THREAD

**Issue by jchidley** [bernhard-42/jupyter-cadquery#54]
I'm sure that it's obvious to some but how do you name items in the tree view, currently mine are named Group, Part_0, Parent_1, Edges_1, Part_2 etc.

**Comment by jchidley** [comment]
Answer: turn it into a Part

```python
import cadquery
from jupyter_cadquery.viewer.client import (Part, show)
result = cadquery.Workplane("front").box(2.0, 2.0, 0.5)
box = Part(result, "Box")
show(box)
```

**Comment by bernhard-42** [comment]
Correct, `Part` and `PartGroup` are the containers of jupyter-cadquery.
You can also use a CadQuery `Assembly`and jupyter-cadquery will transform it to a `PartGroup` hierarchy using the names given in the `Assembly`.
