### ISSUE TITLE
transparent sidebar backgound

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/jupyter-cadquery#69]
A such option would be appreciated to save space, which is necessary when working with an IDE.

Inspirations:

FreeCAD with [Glass addon](https://github.com/triplus/Glass):
![image](https://user-images.githubusercontent.com/1665542/159947191-64c59423-2834-41bc-b163-241847d923a5.png)

SolidWorks with transparent FeatureManager:
![image](https://user-images.githubusercontent.com/1665542/159946784-86eb93ad-a001-4119-84b5-399557f864cb.png)

**Comment by bernhard-42** [comment]
@roipoussiere I've built a new version that features a glass mode ;-) 

Would you like to give it a try and provide feedback? https://bernhard-42.github.io/three-cad-viewer/example.html

Btw. it also features auto-switch to dark mode if browser is used in dark mode

![glass](https://user-images.githubusercontent.com/954408/160236208-ae3ec91b-f35f-45d9-a671-370b4877a0cd.gif)

**Comment by bernhard-42** [comment]
The minimum width needed is `cadWidth=800`
Below 1000, "Transparent", "Black Edges" and "Explode" will be abbreviated. For `cadWidth >= 1000` they are kept in long form.

I don't want to change the UI too much in this major release.  Maybe I group the radio buttons behind some drop down menu later, ...

**Comment by bernhard-42** [comment]
Abbreviations are ugly ...
Changed the menu slightly

![image](https://user-images.githubusercontent.com/954408/160252567-56d808b0-b08d-40c1-ae43-53d66b82ded4.png)

Now the minimum width is 700px for glass mode.

What do you think?

**Comment by roipoussiere** [comment]
> I've built a new version that features a glass mode ;-)

Awesome! 😍

There is a thin border around the tree area in darkmode, that doesn't appear on you last screenshot, is it intentional?

![image](https://user-images.githubusercontent.com/1665542/160389301-774ec087-8a26-4e47-ab64-c513c2ae85dd.png)

> Btw. it also features auto-switch to dark mode if browser is used in dark mode

Perfect! 😍

> Changed the menu slightly

I like it! 😍

**Comment by bernhard-42** [comment]
> There is a thin border around the tree area in darkmode

What OS and browser are you using?

Brave  / Mac
<img width="277" alt="image" src="https://user-images.githubusercontent.com/954408/160467864-50b86b53-8f9f-4eed-9267-c3c1f9cb37db.png">

Firefox / Mac
<img width="277" alt="image" src="https://user-images.githubusercontent.com/954408/160468299-1a125208-d43a-4989-8cdc-3c4469074630.png">

So on the Mac

**Comment by roipoussiere** [comment]
Ubuntu 21.10, Firefox 98

**Comment by roipoussiere** [comment]
The discussion can continue on #77.

Thank you so much for your reactivity. :)
