### ISSUE TITLE
Hexapod mates example: axes don't follow objects when using explode function

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/jupyter-cadquery#72]
Steps to reproduce: 
1. Got to https://bernhard-42.github.io/three-cad-viewer/example.html;
2. Select *Hexapod mates* example;
3. check **explode** option;
4. click on play: the axes doesn't follow the trajectory of their related objects.

![image](https://user-images.githubusercontent.com/1665542/160088267-752a8705-0b6d-4834-b916-7cc2c7ecde68.png)

I don't know if this is an error on the example or on the jcq project...

**Comment by bernhard-42** [comment]
Still fine tuning ...

**Comment by bernhard-42** [comment]
The explode algorithm calculates the center of each object (not of the group including the underlying hierarchy)
It will then use as a direction for each object the axis from the origin (or the bounding box center) to the center of the object.
As such a mate and the object it belongs to usually will have a different angle of the trajectory (since center of mate and center of its object are not identical)

**Comment by bernhard-42** [comment]
@roipoussiere This should now be fixed with 1.5.6
![image](https://user-images.githubusercontent.com/954408/161131929-d38f0fe5-17e7-4d5c-9b0b-b3504cad81ad.png)

**Comment by roipoussiere** [comment]
In the current live example, I get this:

![image](https://user-images.githubusercontent.com/1665542/161163803-e838346e-9dc6-4c4e-b885-a7bf3f91111d.png)

When I click on explode, I was expecting the small axes to be positioned on the corresponding axes on the parts.

But I suppose the axes themselves are concerned by the *explode*, so they can't be aligned anymore, so it's probably a correct behavior.

**Comment by bernhard-42** [comment]
Got it. 
For the explode algorithm, the mates/axes are simple objects without meaning. Hence they will be exploded properly. One advantage is that one can see alinement mates and how they align by going backwards in the explosion animation.
In general, helpers like mates are not the best use case for the explode algorithm

**Comment by roipoussiere** [comment]
Ok I think this can be closed now, since you fixed this.
