### ISSUE TITLE
Highlight the selected view

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/jupyter-cadquery#74]
When the user selects a view (like iso, front, etc), I could be practical to highlight it until the view is updated.

This way the user can quickly see which one is used.

**Comment by bernhard-42** [comment]
You mean keep the button highlighted until another button is pressed or the object is moved?

**Comment by roipoussiere** [comment]
both

**Comment by bernhard-42** [comment]
Pretty easy to implement and actually helpful:

![highlight](https://user-images.githubusercontent.com/954408/160104108-dbe378b3-92e9-4920-9d4a-3116c31a6049.gif)

Is this what you had in mind?

Of course, if one rotates the object and hits by chance one of the predefined directions, buttons will not be highlighted

**Comment by roipoussiere** [comment]
> Is this what you had in mind?

Yep, exactly!

**Comment by bernhard-42** [comment]
I'd like to keep it subtle ...

**Comment by roipoussiere** [comment]
Oh I just realized that this was actually published on https://github.com/bernhard-42/three-cad-viewer/commit/4cfe20439b8975c2dd5cf8ccab028e859fe86370, so I'm closing this now, thank you!
