### ISSUE TITLE
Move the animation bar on the top

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/jupyter-cadquery#75]
The animation bar already appears trunked on my (1680*1050) monitor:

![image](https://user-images.githubusercontent.com/1665542/160453338-c15909d1-00d5-4104-96ae-5e434304843b.png)

You can notice the scroll bar on the right, meaning the content doesn't fit on the screen.

It's annoying because I must:
- scroll up each time I want to access the top tool bar;
- scroll down each time I want to access to animation bar.

I know that it's harder to correctly position elements vertically than horizontally, so I would suggest to move the bar upper on the screen, for instance on the right of the tree panel:

![Screenshot_20220328_193110](https://user-images.githubusercontent.com/1665542/160454712-7a40c028-b59f-4691-b7ce-d4ae7b97a309.png)

**Comment by bernhard-42** [comment]
`jcv` has two parameters `-h` and `-w`. Unfortunately, they are not supported by the docker version. I need to add them. 
So the right approach will be to set the height when starting jcv. I've created https://github.com/bernhard-42/jupyter-cadquery/issues/76

**Comment by bernhard-42** [comment]
@roipoussiere Please try
`docker run -it --rm -p 8888:8888 --name jcq -e "CAD_HEIGHT=520" -e "CAD_WIDTH=700" -p 5555:5555 bwalter42/jupyter_cadquery:3.0.0 -v`
This should open a small window and the animation bar should be visible.
