### ISSUE TITLE
a border migh appear in glass mode

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/jupyter-cadquery#77]
Appears on Ubuntu 21.10, Firefox 98:

![image](https://user-images.githubusercontent.com/1665542/160485307-60c8f4f3-a241-47b9-b640-8cb236ce662f.png)

See https://github.com/bernhard-42/jupyter-cadquery/issues/69#issuecomment-1080538911

Since it's a bug, I create this issue in order to close #69.

**Comment by bernhard-42** [comment]
@roipoussiere This should be fixed in 1.5.6

**Comment by bernhard-42** [comment]
Please close when you think it's done. Thanks

**Comment by roipoussiere** [comment]
Tested and approved! :ok_hand: 
![image](https://user-images.githubusercontent.com/1665542/161208879-6c4f6318-55be-470c-b847-7e11e01f2a30.png)
