### ISSUE TITLE
add options to hide some tools in toolbar

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/jupyter-cadquery#78]
When using the viewer with a small width, the toolbar might be too wide.

Hiding some tools will make it lighter, but in order to still be able to use them if necessary, I would suggest 3 states:
- **hidden**: the tool is not visible on the bar;
- **visible**: the tool is not visible on the bar;
- **collapsed**: the tool is moved in the *More* dropdown list;

I'm not sure what is the best way to do it. Maybe adding two more options that use tools identifiers in arrays:

```js
const options = {
    // ...
    hide_tools: ['ortho', 'explode', 'axes0', 'pin_view'],
    collapse_tools: ['axes', 'grid', 'transparent', 'black_edge', 'explode', 'help']
}
```

**Comment by bernhard-42** [comment]
I'm not sure I want to spend time on this. We are now down to 700px width of the CAD window which is an overall size of 700x525. I don't believe working with CAD models on smaller canvases really makes sense

What is your use case that 700px width is too large?

**Comment by roipoussiere** [comment]
> What is your use case that 700px width is too large?

The VSCode extension I'm working on:

![image](https://user-images.githubusercontent.com/1665542/160679430-fc9fd1b5-fcad-475c-be01-db41eab1c4f1.png)

I don't want to impose a large view panel to users, neither to force them to hide the VSCode tree view (that I plan to use later to replace the CadQuery tree view).

The options I suggested above will be defined in the extension option by the user according to their needs.

**Comment by bernhard-42** [comment]
What width do you want to achieve? Just to understand whether it would be achievable...

**Comment by roipoussiere** [comment]
Ideally a minimum of 450px, which is just enough to display the view buttons:

![image](https://user-images.githubusercontent.com/1665542/160682173-245d3e52-18fd-4181-b12a-1a160bcbbdc7.png)

**Comment by bernhard-42** [comment]
You could also use the "no tools" mode and add your own buttons? You then have the full freedom of width and height (and I would just remove the limitation of width>=700px)

This is where you would start:

https://github.com/bernhard-42/three-cad-viewer/blob/ea80d773ddabc60b454d8f886d217833cdbf199d/src/display.js#L511-L525

**Comment by roipoussiere** [comment]
Ok I think I can do that, thanks!

**Comment by bernhard-42** [comment]
but you wouldn't have the tree, comes to my mind now.
How about this:
You use the glass mode with width 450px leading to

<img width="456" alt="image" src="https://user-images.githubusercontent.com/954408/160693876-f6250c38-4307-4227-b9d3-a1f0a77b27e7.png">

Then run this code in the browser console:

```javascript
tags = ["tcv_axes", "tcv_axes0", "tcv_grid", "tcv_ortho"]
tags.forEach((tag) => {
    console.log(1, tag)
    var el = viewer.display._getElement(tag);
    console.log(2, el)
    el.style.display = "none";
    el.nextElementSibling.style.display = "none";
})
```

It should lead to 

<img width="456" alt="image" src="https://user-images.githubusercontent.com/954408/160693970-59f47fbd-fb6a-428b-b03a-cd9369e82060.png">

Would that make sense?

**Comment by bernhard-42** [comment]
and of course, you would remove the pin button in vscode.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/954408/160694985-fbe03dd2-04d3-42e1-a1ca-89c37faff329.png">

**Comment by roipoussiere** [comment]
Thank you! I will investigate this later.

**Comment by bernhard-42** [comment]
I have added a function to the next release to selectively enable/disable elements in the tollbar:

Disable:

```javascript
viewer.trimUI(["axes", "axes0", "grid", "ortho", "more"], false)
```

Enable:

```javascript
viewer.trimUI(["axes", "axes0", "grid", "ortho", "more"], true)
```

Now you can easily go down to width of 400px

<img width="406" alt="image" src="https://user-images.githubusercontent.com/954408/160697247-6118917f-338e-47ef-80cc-95fb2e13b66d.png">


Since you have to create the viewer component in the web view of VS Code, you should be able to call this function, right?

**Comment by bernhard-42** [comment]
ok, for this small window the help dialog is too large :-(
So I added "help" to the function:

```javascript
viewer.trimUI(["axes", "axes0", "grid", "ortho", "more", "help"], true)
```

Now 330px is the min width:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/954408/160698136-5fb3cbfb-0385-4b61-b169-282eb4d889d0.png">

Not sure how useful this is, however it is possible

**Comment by roipoussiere** [comment]
bernhard-42:

> I'm not sure I want to spend time on this.

also bernhard-42, two hours and a few commits later:

> Now 330px is the min width

😁 Thank you so much, this will be very useful! ❤️

**Comment by bernhard-42** [comment]
@roipoussiere I just cloned your repo, did a `yarn install`, added the trimUI line to the index html file:

![image](https://user-images.githubusercontent.com/954408/161125808-48534a29-aa98-4531-9f4d-2a3721aef172.png)

and it works:

![image](https://user-images.githubusercontent.com/954408/161125881-9fc31886-4dec-47b9-b435-13db2f4deaf9.png)

However, sometimes the cadquery view shows an empty CAD viewer on start and one has to save the python file again to see the object. And if it is empty, then trimUI didn't run

**Comment by bernhard-42** [comment]
![image](https://user-images.githubusercontent.com/954408/161127422-96ee58e9-72a2-4f25-8196-ef04f02032e4.png)

turns out in this case the `render` function is not called, only `update_view`
