### ISSUE TITLE
Syntax error when setting darkmode

### ISSUE THREAD

**Issue by yvanblanchard** [bernhard-42/jupyter-cadquery#93]
Hello,

I followed the recommendations for a windows install with conda, but I got a syntax error when setting the darkmode them:

![image](https://user-images.githubusercontent.com/63931618/214688505-79ca54ba-2cd3-441e-a479-39135da8a9e9.png)

Could you please help ?
Thank you.

**Comment by bernhard-42** [comment]
Please remove the "[1]:" at the beginning, you've copied too much

**Comment by bernhard-42** [comment]
I will change the Readme and remove the ipython prefix "[1]:"  in the next release

**Comment by yvanblanchard** [comment]
Ok thank you!
sorry for my silly question :-)

I also noticed that we must pay attention at indentation as well
![image](https://user-images.githubusercontent.com/63931618/214690834-7908b141-196f-456e-ba10-de527ed33fb3.png)
